package:
  name: mlxtend
  version: "0.4.1"

source:
  fn: mlxtend-0.4.1.tar.gz
  url: https://files.pythonhosted.org/packages/e2/e5/12927e24d3161460a651b7ed1724a45e39b7bb5e6854b1d63812dd9977a6/mlxtend-0.4.1.tar.gz
  md5: 113df88a3b3881f3d209705fdc156696
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - mlxtend = mlxtend:main
    #
    # Would create an entry point called mlxtend that calls mlxtend.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10.4
    - scipy >=0.17
    - scikit-learn >=0.17.1
    - pandas >=0.17
    - matplotlib

  run:
    - python
    - numpy >=1.10.4
    - scipy >=0.17
    - scikit-learn >=0.17.1
    - pandas >=0.17
    - matplotlib

test:
  # Python imports
  imports:
    - mlxtend
    - mlxtend._base
    - mlxtend.classifier
    - mlxtend.cluster
    - mlxtend.data
    - mlxtend.evaluate
    - mlxtend.externals
    - mlxtend.feature_extraction
    - mlxtend.feature_selection
    - mlxtend.file_io
    - mlxtend.general_plotting
    - mlxtend.math
    - mlxtend.preprocessing
    - mlxtend.regression_utils
    - mlxtend.regressor
    - mlxtend.text
    #- mlxtend.tf_classifier
    #- mlxtend.tf_cluster
    #- mlxtend.tf_regressor
    - mlxtend.utils


about:
  home: https://github.com/rasbt/mlxtend
  license: BSD License
  summary: 'Machine Learning Library Extensions'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
